# _config.yml

url: "https://mehdiha.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/processinformatique" # the subpath of your site, e.g. /blog
title: "Process informatique" # the name of your site, e.g. ACME Corp.

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

plugins:
  - jekyll-postcss

exclude:
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json

include: ["node_modules/tailwindcss"]